// Reference na canonical product names (mula sa master list ng client).
// Ginagamit para sa autocomplete suggestions sa Products page — iwas misspelling/mismatch.
export const PRODUCT_REFERENCE = [
  'A&W Root Beer',
  'Bear Brand Sterilized 200ml',
  'Bread Pan',
  'C2 Apple 500ml',
  'Cali Apple',
  'Cali Pineapple',
  'Chips Delight Chocolate',
  'Chuckie 250ml',
  'Clover Chips',
  'Coca Cola Original 320ml',
  'Del Monte Fibre Enriched 240ml',
  'Del Monte Four Seasons',
  'Del Monte Pineapple Ace 240ml',
  'DM Delight 400ml',
  'Dutchmill Strawberry',
  'Gatorade Blue Bolt 500ml',
  'Gatorade Tropical Fruit 500ml',
  'J&J Piattos Cheese',
  'J&J Vcut BBQ',
  'Knick Knacks',
  'Kopiko Lucky Day 180ml',
  'Lays Sour Cream & Onion',
  'Loaded White Chocolate',
  'Mang Juan Chicken Skin',
  'Milo 180ml',
  'Moby Caramel',
  'Mogu Mogu Lychee',
  'Mogu Mogu Strawberry',
  'Mountain Dew 320ml',
  'Mug Root Beer',
  'Nescafe Cappuccino',
  'Nescafe Ice Black',
  'Nova Cheddar',
  'Pepsi 320ml',
  'Pepsi Lime Zero Sugar',
  'Pillows Ube',
  'Red Horse 330ml',
  'Regent Cheese Ring',
  'Regent Snaku 60g',
  'Ri-Chee',
  'Roller Coaster',
  'Royal Lychee',
  'Royal Strawberry 320ml',
  'Royal Tru Orange 320ml',
  'San Mig Apple',
  'San Mig Light 330ml',
  'Sprite 320ml',
  'Stick-O Handy Pack',
  'Sting Red 290ml',
  'Sugo Salted Peanuts',
  'Summit 500ml',
  'Tropicana Twister 355ml',
  'Vinut Mixed Fruit 250ml',
  'Wilkins 500ml',
  'Zesto Big Apple',
];
